import { Checkbox } from './src/components/form/checkbox/Checkbox';
import { TextInput } from './src/components/form/textinput/TextInput';
import { Store } from './src/shared/store/Store';
import { Select } from './src/components/form/select/Select';
import { Completion } from './src/components/form/completion/Completion';
import { Modax } from './src/components/interaction/dialog/Modax';
import { Dialog } from './src/components/interaction/dialog/Dialog';
import { Button } from './src/components/interaction/button/Button';
import { FormField } from './src/components/form/formfield/FormField';
import { Loading } from './src/components/display/loading/Loading';
import { CharCount } from './src/components/form/charcount/CharCount';
import { Options } from './src/components/form/options/Options';
import { ContactChat } from './src/components/specialized/contacts/ContactChat';
import { TicketList } from './src/components/specialized/list/TicketList';
import { ContactDetails } from './src/components/specialized/contacts/ContactDetails';
import { TembaList } from './src/components/specialized/list/TembaList';
import { ContactSearch } from './src/components/specialized/contactsearch/ContactSearch';
import { VectorIcon } from './src/shared/vectoricon/VectorIcon';
import { Alert } from './src/components/display/alert/Alert';
import { Omnibox } from './src/components/form/omnibox/Omnibox';
import { Tip } from './src/components/display/tip/Tip';
import { TembaMenu } from './src/components/specialized/list/TembaMenu';
import { Anchor } from './src/components/interaction/anchor/Anchor';
import { Dropdown } from './src/components/interaction/dropdown/Dropdown';
import { TabPane } from './src/components/layout/tabpane/TabPane';
import { Tab } from './src/components/layout/tabpane/Tab';
import Label from './src/components/form/label/Label';
import { ContactName } from './src/components/specialized/contacts/ContactName';
import { ContactUrn } from './src/components/specialized/contacts/ContactUrn';
import { ContactFields } from './src/components/specialized/contacts/ContactFields';
import { ContactFieldEditor } from './src/components/specialized/contacts/ContactFieldEditor';

import { ContactBadges } from './src/components/specialized/contacts/ContactBadges';
import { ContactPending } from './src/components/specialized/contacts/ContactPending';
import { TembaSlider } from './src/components/form/slider/TembaSlider';
import { RunList } from './src/components/specialized/list/RunList';
import { FlowStoreElement } from './src/shared/store/FlowStoreElement';
import { ContactNameFetch } from './src/components/specialized/contacts/ContactNameFetch';
import { DatePicker } from './src/components/form/datepicker/DatePicker';
import { FieldManager } from './src/components/form/fields/FieldManager';
import { SortableList } from './src/components/specialized/list/SortableList';
import { ContentMenu } from './src/components/specialized/list/ContentMenu';
import { TembaDate } from './src/components/display/date/TembaDate';
import { Compose } from './src/components/communication/compose/Compose';
import { Lightbox } from './src/components/interaction/lightbox/Lightbox';
import { ColorPicker } from './src/components/form/colorpicker/ColorPicker';
import { Resizer } from './src/components/layout/resizer/Resizer';
import { Thumbnail } from './src/components/display/thumbnail/Thumbnail';
import { NotificationList } from './src/components/specialized/list/NotificationList';
import { WebChat } from './src/components/communication/webchat/WebChat';
import { ImagePicker } from './src/components/form/imagepicker/ImagePicker';
import { Mask } from './src/components/form/mask/Mask';
import { TembaUser } from './src/components/specialized/user/TembaUser';
import { TemplateEditor } from './src/components/specialized/templates/TemplateEditor';
import { Toast } from './src/components/display/toast/Toast';
import { Chat } from './src/components/communication/chat/Chat';
import { MediaPicker } from './src/components/form/mediapicker/MediaPicker';
import { Editor } from './src/components/specialized/flow/Editor';
import { EditorNode } from './src/components/specialized/flow/EditorNode';
import { StickyNote } from './src/components/specialized/flow/StickyNote';
import { ContactNotepad } from './src/components/specialized/contacts/ContactNotepad';
import { ProgressBar } from './src/components/display/progress/ProgressBar';
import { StartProgress } from './src/components/display/progress/StartProgress';
import { ShortcutList } from './src/components/specialized/list/ShortcutList';
import { PopupSelect } from './src/components/form/select/PopupSelect';
import { UserSelect } from './src/components/form/select/UserSelect';
import { WorkspaceSelect } from './src/components/form/select/WorkspaceSelect';
import { TembaChart } from './src/components/display/chart/TembaChart';
import { RangePicker } from './src/components/form/datepicker/RangePicker';

export function addCustomElement(name: string, comp: any) {
  if (!window.customElements.get(name)) {
    window.customElements.define(name, comp);
  }
}

addCustomElement('temba-anchor', Anchor);
addCustomElement('temba-alert', Alert);
addCustomElement('temba-store', Store);
addCustomElement('temba-textinput', TextInput);
addCustomElement('temba-datepicker', DatePicker);
addCustomElement('temba-range-picker', RangePicker);
addCustomElement('temba-date', TembaDate);
addCustomElement('temba-completion', Completion);
addCustomElement('temba-checkbox', Checkbox);
addCustomElement('temba-select', Select);
addCustomElement('temba-options', Options);
addCustomElement('temba-loading', Loading);
addCustomElement('temba-lightbox', Lightbox);
addCustomElement('temba-button', Button);
addCustomElement('temba-omnibox', Omnibox);
addCustomElement('temba-tip', Tip);
addCustomElement('temba-contact-name', ContactName);
addCustomElement('temba-contact-name-fetch', ContactNameFetch);
addCustomElement('temba-contact-field', ContactFieldEditor);
addCustomElement('temba-contact-fields', ContactFields);
addCustomElement('temba-field-manager', FieldManager);
addCustomElement('temba-urn', ContactUrn);
addCustomElement('temba-content-menu', ContentMenu);

addCustomElement('temba-field', FormField);
addCustomElement('temba-dialog', Dialog);
addCustomElement('temba-modax', Modax);
addCustomElement('temba-charcount', CharCount);
addCustomElement('temba-contact-chat', ContactChat);
addCustomElement('temba-contact-details', ContactDetails);
addCustomElement('temba-ticket-list', TicketList);
addCustomElement('temba-notification-list', NotificationList);
addCustomElement('temba-list', TembaList);
addCustomElement('temba-sortable-list', SortableList);
addCustomElement('temba-run-list', RunList);
addCustomElement('temba-flow-details', FlowStoreElement);
addCustomElement('temba-label', Label);
addCustomElement('temba-menu', TembaMenu);
addCustomElement('temba-contact-search', ContactSearch);
addCustomElement('temba-icon', VectorIcon);
addCustomElement('temba-dropdown', Dropdown);
addCustomElement('temba-tabs', TabPane);
addCustomElement('temba-tab', Tab);
addCustomElement('temba-contact-badges', ContactBadges);
addCustomElement('temba-contact-pending', ContactPending);
addCustomElement('temba-slider', TembaSlider);
addCustomElement('temba-content-menu', ContentMenu);
addCustomElement('temba-compose', Compose);
addCustomElement('temba-color-picker', ColorPicker);
addCustomElement('temba-resizer', Resizer);
addCustomElement('temba-thumbnail', Thumbnail);
addCustomElement('temba-webchat', WebChat);
addCustomElement('temba-image-picker', ImagePicker);
addCustomElement('temba-mask', Mask);
addCustomElement('temba-user', TembaUser);
addCustomElement('temba-template-editor', TemplateEditor);
addCustomElement('temba-toast', Toast);
addCustomElement('temba-chat', Chat);
addCustomElement('temba-media-picker', MediaPicker);
addCustomElement('temba-flow-editor', Editor);
addCustomElement('temba-flow-node', EditorNode);
addCustomElement('temba-sticky-note', StickyNote);
addCustomElement('temba-contact-notepad', ContactNotepad);
addCustomElement('temba-progress', ProgressBar);
addCustomElement('temba-start-progress', StartProgress);
addCustomElement('temba-shortcuts', ShortcutList);
addCustomElement('temba-popup-select', PopupSelect);
addCustomElement('temba-user-select', UserSelect);
addCustomElement('temba-workspace-select', WorkspaceSelect);
addCustomElement('temba-chart', TembaChart);
