import { Checkbox } from './src/checkbox/Checkbox';
import { TextInput } from './src/textinput/TextInput';
import { Store } from './src/store/Store';
import { Select } from './src/select/Select';
import { Completion } from './src/completion/Completion';
import { Modax } from './src/dialog/Modax';
import { Dialog } from './src/dialog/Dialog';
import { Button } from './src/button/Button';
import { FormField } from './src/formfield/FormField';
import { Loading } from './src/loading/Loading';
import { CharCount } from './src/charcount/CharCount';
import { Options } from './src/options/Options';
import { ContactChat } from './src/contacts/ContactChat';
import { ContactHistory } from './src/contacts/ContactHistory';
import { ContactList } from './src/list/ContactList';
import { ContactDetails } from './src/contacts/ContactDetails';
import { TembaList } from './src/list/TembaList';
import { ContactSearch } from './src/contactsearch/ContactSearch';
import { VectorIcon } from './src/vectoricon/VectorIcon';
import { Alert } from './src/alert/Alert';
import { Omnibox } from './src/omnibox/Omnibox';
import { Tip } from './src/tip/Tip';

window.customElements.define('temba-alert', Alert);
window.customElements.define('temba-store', Store);
window.customElements.define('temba-textinput', TextInput);
window.customElements.define('temba-completion', Completion);
window.customElements.define('temba-checkbox', Checkbox);
window.customElements.define('temba-select', Select);
window.customElements.define('temba-options', Options);
window.customElements.define('temba-loading', Loading);
window.customElements.define('temba-button', Button);
window.customElements.define('temba-omnibox', Omnibox);
window.customElements.define('temba-tip', Tip);

window.customElements.define('temba-field', FormField);
window.customElements.define('temba-dialog', Dialog);
window.customElements.define('temba-modax', Modax);
window.customElements.define('temba-charcount', CharCount);
window.customElements.define('temba-contact-history', ContactHistory);
window.customElements.define('temba-contact-chat', ContactChat);
window.customElements.define('temba-contact-details', ContactDetails);
window.customElements.define('temba-contacts', ContactList);
window.customElements.define('temba-list', TembaList);
window.customElements.define('temba-contact-search', ContactSearch);
window.customElements.define('temba-icon', VectorIcon);
