name: 'Copilot Setup Steps'

# Triggers: Run on pull requests and pushes to prepare environment for agent tasks
on:
  pull_request:
  push:

jobs:
  setup:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Setup Node.js environment with version matching the project (Node.js 20)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      # Cache yarn dependencies to speed up future runs
      # Uses yarn.lock as the cache key for dependency consistency
      - name: Cache yarn dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.yarn
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      
      # Install project dependencies using yarn
      # Skip Puppeteer Chromium download since it's not needed for setup
      - name: Install dependencies
        run: yarn install
        env:
          PUPPETEER_SKIP_DOWNLOAD: true
      
      # Pre-build the project to warm up the environment
      # This compiles TypeScript, processes SVG icons, and creates distribution files
      - name: Build project
        run: yarn build
        
      # Cache the built output to speed up subsequent operations
      - name: Cache build output
        uses: actions/cache@v4
        with:
          path: |
            dist
            out-tsc
            static/svg/index.svg
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-